swnapi/applications/home/urls.py
from django.urls import path
from . import views

app_name="home_app"

urlpatterns = [
    path(
        '', 
        views.HomeView.as_view(),
        name='index',
    ),
    path(
        'servicio/<pk>/', 
        views.ServiciosDetailView.as_view(),
        name='servicios-detail',
    ),
]

swnapi/swnapi/urls.py
"""
"""
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
#
from applications.home.views import Error404View, Error505View

urlpatterns = [
    path('administrar/', admin.site.urls),
    path('', include('applications.tienda.urls'), name="tienda"),
    path('', include('applications.neun.urls'), name='neun'),
    path('', include('applications.home.urls'), name="home"),
    path('', include('applications.examen.urls'), name="examen"),
    path('', include('applications.sheriff.urls'), name="sheriff"),
    path('', include('applications.portfolio.urls'), name="portfolio"),

    path('', include('applications.cursos.routes')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

handler404 = Error404View.as_view()

handler500 = Error505View.as_error_view()

swnapi/applications/home/models.py
from django.db import models

# Create your models here.
from django_quill.fields import QuillField

# Django
from django.conf import settings


class Servicios(models.Model):
    """ Servicios api  """

    name = models.CharField(
        'nombre', 
        max_length=120
    )
    content = QuillField(
        'contenido'
    )
    video = models.URLField(blank=True)
    publicado = models.BooleanField(default=False)
    visits = models.IntegerField(default=0)

    class Meta:
        verbose_name = 'Servicio'
        verbose_name_plural = 'Servicios API'

    def __str__(self):
        return self.name

        

swnapi/applications/home/views.py
from django.shortcuts import render

from django.views.generic import TemplateView, DetailView

from .models import Servicios


class HomeView(TemplateView):
    template_name = "home/index.html"


class ServiciosDetailView(DetailView):
    model = Servicios
    template_name = "home/servicios.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["servicios"] = Servicios.objects.all() 
        return context
    
    def get_object(self, queryset=None):
        # Use a custom queryset if provided; this is required for subclasses
        # like DateDetailView
        if queryset is None:
            queryset = self.get_queryset()
        # Next, try looking up by primary key.
        pk = self.kwargs.get(self.pk_url_kwarg)
        slug = self.kwargs.get(self.slug_url_kwarg)
        if pk is not None:
            queryset = queryset.filter(pk=pk)
        # Next, try looking up by slug.
        if slug is not None and (pk is None or self.query_pk_and_slug):
            slug_field = self.get_slug_field()
            queryset = queryset.filter(**{slug_field: slug})
        # If none of those are defined, it's an error.
        if pk is None and slug is None:
            raise AttributeError(
                "Generic detail view %s must be called with either an object "
                "pk or a slug in the URLconf." % self.__class__.__name__
            )
        try:
            # Get the single item from the filtered queryset
            obj = queryset.get()
        except queryset.model.DoesNotExist:
            obj = Servicios.objects.first()
        return obj
    

class Error404View(TemplateView):
    template_name = "home/error_404.html"


class Error505View(TemplateView):
    template_name = "home/error_500.html"

    @classmethod
    def as_error_view(cls):

        v = cls.as_view()
        def view(request):
            r = v(request)
            r.render()
            return r
        return view

    

swnapi/templates/home/base_home.html
{% extends "base.html" %}

{% load static %}

{% block css %}
  <meta property="og:type" content="website">
  <meta property="og:locale" content="es_PE">
  <meta property="og:site_name" content="Deporstart">
  <meta property="og:url" content="https://servicios.neunapp.com">
  <link rel="stylesheet" href="{% static 'css/foundation.min.css' %}?rand=23423423">
  <link rel="stylesheet" href="{% static 'css/app.css' %}?rand=23423423">

 <!-- Global site tag (gtag.js) - Google Analytics -->
    <script async src="https://www.googletagmanager.com/gtag/js?id=G-83GJSEREY1"></script>
    <script>
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'G-83GJSEREY1');
    </script>

{% endblock css %}

{% block js %}
  <script src="{% static 'js/jquery.js' %}"></script>
  <script src="{% static 'js/foundation.min.js' %}"></script>
  <script src="{% static 'js/app.js' %}"></script>

{% endblock js %}

swnapi/templates/home/blog_add.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  {{ form }}
</body>
</html>

swnapi/templates/home/error_404.html
{% extends "home/base_home.html" %}

{% load static %}

{% block title %}Api Web para pruebas - neunapp {% endblock %}

{% block description %} Servicios REST gratuitos para hacer practicas en desarrollo frontend.  {% endblock description %}

{% block tags %} servicios rest gratis, api gratis, api para programacion web{% endblock tags %}

{% block content %}
    {% include "includes/header.html" %}
    
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="grid-y grid-margin-y align-center">
                <div class="cell small-12 medium-9 large-6">
                    <div class="callout alert">
                        <h1 style="font-size: 18px; font-weight: bold;">Ups, aun no tenemos esta pagina :(</h1>
                        <a href="{% url 'home_app:index' %}">Volve a inicio</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

swnapi/templates/home/error_500.html
{% extends "home/base_home.html" %}

{% load static %}

{% block title %}Api Web para pruebas - neunapp {% endblock %}

{% block description %} Servicios REST gratuitos para hacer practicas en desarrollo frontend.  {% endblock description %}

{% block tags %} servicios rest gratis, api gratis, api para programacion web{% endblock tags %}

{% block content %}
    {% include "includes/header.html" %}
    
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="grid-y grid-margin-y align-center">
                <div class="cell small-12 medium-9 large-6">
                    <div class="callout alert">
                        <h1 style="font-size: 18px; font-weight: bold;">:( Al parecer has encontrado un error :(</h1>
                        <p>Por favor si puedes ayudanos reportando el error a: @neunapp (instagram, github)</p>
                        <a href="{% url 'home_app:index' %}">Volve a inicio</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

swnapi/templates/home/index.html
{% extends "home/base_home.html" %}

{% load static %}

{% block title %}Api Web para pruebas - neunapp {% endblock %}

{% block description %} Servicios REST gratuitos para hacer practicas en desarrollo frontend.  {% endblock description %}

{% block tags %} servicios rest gratis, api gratis, api para programacion web{% endblock tags %}

{% block content %}
    {% include "includes/header.html" %}
    
    <div class="grid-container">
        <div class="grid-x grid-margin-x align-center">
            <div class="grid-y grid-margin-y align-center">
                <div class="cell small-12 medium-9 large-6">
                    <div class="callout">
                        <h1 style="font-size: 18px; font-weight: bold;">Servicios REST para Practicas</h1>
                        <p>Servicios rest api sencillos de utilizar, con los que podemos practicar desarrollo frontend. </p>
                        <a href="{% url 'home_app:servicios-detail' 0 %}">Ver servicios</a>
                    </div>
                </div>
            </div>
        </div>
    </div>

{% endblock content %}

swnapi/templates/home/servicios.html
{% extends "home/base_home.html" %}

{% load static %}

{% block title %} Servicios REST API para practicas {% endblock %}

{% block description %} api gratuitas para practicar vuejs reactjs y otros frontend {% endblock description %}

{% block tags %} api gratuitas para programacion web {% endblock tags %}

{% block content %}
    {% include "includes/header.html" %}
    
    <div class="grid-container fluid" style="padding: 2em;">
        <div class="grid-x grid-margin-x">
            <div class="cell small-12 medium-3 large-2">
                <ul class="vertical menu">
                    {% for servicio in servicios  %}
                        <li>
                            <a
                                {% url 'home_app:servicios-detail' servicio.id as home_url %}
                                {% if request.get_full_path == home_url %}
                                    class="active-link"
                                {% else %} 
                                    class="link" 
                                {% endif %}
                                href="{% url 'home_app:servicios-detail' servicio.id %}">
                                {{ servicio.name }}
                            </a>
                        </li>
                    {% endfor %}
                </ul>
            </div>
            <div class="cell samll-12 medium-9 large-10">
                <p> {{ object.content | safe }} </p>
            </div>
        </div>
    </div>

{% endblock content %}